#!/usr/bin/env python3
"""
Threes 지원 · 개인정보 처리방침 페이지 생성기 (GitHub Pages).
  python3 build.py   →  index.html, privacy.html (언어 자동 이동) + <lang>/index.html, <lang>/privacy.html
문구는 아래 CONTENT 에서 고친다. 앱 스토어에는 언어별 주소를 넣는다:
  지원:   https://ohtt-ios.github.io/Threes-public/<lang>/
  개인정보: https://ohtt-ios.github.io/Threes-public/<lang>/privacy.html
"""
import html
from pathlib import Path

ROOT = Path(__file__).resolve().parent
BASE = "https://ohtt-ios.github.io/Threes-public"
ISSUES = "https://github.com/ohtt-iOS/Threes-public/issues"
APP_STORE = "https://apps.apple.com/app/id6812920395"
EFFECTIVE = "2026-09-18"
LANG_NAMES = {"en": "English", "ko": "한국어", "ja": "日本語", "zh-Hans": "简体中文", "zh-Hant": "繁體中文",
              "vi": "Tiếng Việt", "es": "Español", "pt-BR": "Português (BR)", "th": "ไทย", "id": "Bahasa Indonesia",
              "de": "Deutsch", "fr": "Français", "it": "Italiano", "ru": "Русский", "tr": "Türkçe", "ms": "Bahasa Melayu", "hi": "हिन्दी", "nl": "Nederlands", "pl": "Polski", "sv": "Svenska"}

def C(support_title, tagline, faq, contact_h, contact_p, contact_link, privacy_link, support_link,
      privacy_title, effective, sections, changes_note):
    return dict(support_title=support_title, tagline=tagline, faq=faq, contact_h=contact_h, contact_p=contact_p,
                contact_link=contact_link, privacy_link=privacy_link, support_link=support_link,
                privacy_title=privacy_title, effective=effective, sections=sections, changes_note=changes_note)

CONTENT = {
"en": C("Threes Support", "Three 3-second clips, stacked into one vertical video diary.",
    [("How do I record?", "Tap the record button. It records for 3 seconds and stops by itself. Do that three times and your three is done. You can also pull a video or photo in from your album."),
     ("Where are my videos?", "Tap Save video on the finished screen and it goes to the Photos app as a 9:16 mp4 with no watermark. Clips are stored only on your phone."),
     ("How long are drafts kept?", "Free keeps up to 3 drafts for 14 days. Pro keeps unlimited drafts for 90 days. A finished three can be re-edited for 7 days."),
     ("What does Pro include, and how do I restore it?", "Threes Pro is a one-time purchase through Apple: custom labels (all 16 templates are already free), 8 more filters with strength control, unlimited drafts. To restore on another device, sign in with the same Apple ID and tap Settings → Restore purchases."),
     ("Can I use my own font?", "Yes. Add a ttf or otf file in Settings → My fonts, or with the + card at the end of the Font tab while editing."),
     ("How do I delete my data?", "Delete a three from Home, or delete the app. Everything lives on your device, so nothing remains anywhere else.")],
    "Contact", "Found a bug or have a question? Open an issue and we'll reply there.", "Open an issue on GitHub",
    "Privacy Policy", "Support",
    "Privacy Policy", f"Effective {EFFECTIVE}",
    [("In short", "Threes has no account and no server of its own. Everything you record stays on your device. We do not collect personal data; the only thing that leaves your phone is anonymous usage statistics (see Network use)."),
     ("Camera and Photos", "Threes asks for the camera to record your clips and for permission to add to Photos so it can save your finished video. Nothing is uploaded anywhere."),
     ("Data on your device", "Clips, thumbnails, drafts, fonts you add and your settings are stored only on your device. They are removed when you delete them in the app or delete the app."),
     ("Purchases", "Threes Pro is sold through Apple's In-App Purchase. Apple handles payment; we never see your payment details or Apple ID. Restoring a purchase also goes through Apple."),
     ("Network use", "The app connects to the internet only to check whether a newer version exists, by asking Apple's App Store about the app's own identifier and your store region, and possibly by fetching a small update-notice file from our hosting. No device identifiers are sent. Threes also uses Google Analytics for Firebase to count how the app is used: which screens open, which templates and filters are chosen, whether a three is finished or a purchase is made. This sends a random app-instance ID, device model, OS version, language and approximate region to Google. It never includes your videos, photos, labels or any account — there is none. No advertising identifier is used and there is no advertising or cross-app tracking."),
     ("Sharing", "When you share a video, it is handed to the app you choose, and that app's privacy policy applies."),
     ("Children", "Threes is not directed at children under 13 and, as described above, collects no personal data from anyone."),
     ("Changes", "If this policy changes, the new version will be posted on this page with a new effective date."),
     ("Contact", f"Questions about privacy: open an issue at {ISSUES}.")],
    ""),
"ko": C("Threes 지원", "3초씩 세 컷, 세로로 이어 붙인 영상 일기.",
    [("어떻게 찍나요?", "촬영 버튼을 누르면 3초 뒤에 알아서 멈춰요. 세 번 찍으면 3컷이 완성됩니다. 앨범에 있는 영상·사진을 가져와도 돼요."),
     ("완성한 영상은 어디에 있나요?", "완성 화면에서 '영상 저장'을 누르면 워터마크 없는 9:16 mp4로 사진 앱에 들어가요. 클립은 휴대폰 안에만 저장됩니다."),
     ("작업 중인 3컷은 얼마나 보관되나요?", "무료는 3개까지 14일, Pro는 개수 제한 없이 90일이에요. 완성한 3컷은 7일 동안 다시 편집할 수 있어요."),
     ("Pro에는 뭐가 들어 있고, 복원은 어떻게 하나요?", "Threes Pro는 Apple을 통한 한 번 결제예요. 나만의 라벨(템플릿 16개는 원래 전부 무료), 필터 8종과 강도 조절, 작업 중 3컷 무제한이 열립니다. 다른 기기에서는 같은 Apple ID로 로그인한 뒤 설정 → 구매 복원을 누르세요."),
     ("내 폰트를 쓸 수 있나요?", "네. 설정 → 내 폰트에서, 또는 편집 화면 폰트 탭 맨 끝의 + 카드에서 ttf·otf 파일을 넣으면 돼요."),
     ("내 데이터는 어떻게 지우나요?", "홈에서 3컷을 지우거나 앱을 삭제하면 끝이에요. 모든 데이터가 기기 안에만 있어서 다른 곳에 남는 게 없습니다.")],
    "문의", "버그나 궁금한 점은 이슈로 남겨 주세요. 거기서 답합니다.", "GitHub에 이슈 남기기",
    "개인정보 처리방침", "지원",
    "개인정보 처리방침", f"시행일 {EFFECTIVE}",
    [("요약", "Threes에는 계정도, 자체 서버도 없어요. 찍은 것은 전부 기기 안에 남고, 개인정보를 수집하지 않습니다. 휴대폰 밖으로 나가는 건 익명 사용 통계뿐이에요(아래 '네트워크 사용')."),
     ("카메라와 사진", "클립을 찍기 위해 카메라 권한을, 완성한 영상을 저장하기 위해 사진 추가 권한을 요청합니다. 어디에도 업로드하지 않아요."),
     ("기기 안의 데이터", "클립, 썸네일, 작업 중인 3컷, 추가한 폰트, 설정은 기기에만 저장됩니다. 앱에서 지우거나 앱을 삭제하면 함께 사라져요."),
     ("결제", "Threes Pro는 Apple 인앱 결제로 판매합니다. 결제는 Apple이 처리하고, 결제 정보나 Apple ID는 저희에게 전달되지 않아요. 구매 복원도 Apple을 통해 이뤄집니다."),
     ("네트워크 사용", "앱은 새 버전이 있는지 확인할 때만 인터넷에 연결해요. Apple App Store에 앱 식별자와 스토어 지역으로 최신 버전을 묻고, 저희 호스팅에서 작은 업데이트 안내 파일을 받아올 수 있습니다. 그리고 앱이 어떻게 쓰이는지 세기 위해 Google Analytics for Firebase를 씁니다. 어떤 화면을 열었는지, 어떤 템플릿·필터를 골랐는지, 3컷을 완성했는지, 결제했는지가 Google에 전송되고, 여기에는 무작위 앱 인스턴스 ID·기기 모델·OS 버전·언어·대략적인 지역이 함께 담깁니다. 영상·사진·라벨 내용이나 계정(없음)은 절대 포함되지 않아요. 광고 식별자는 쓰지 않고, 광고나 앱 간 추적도 없습니다."),
     ("공유", "영상을 공유하면 선택한 앱으로 넘어가며, 그 앱의 개인정보 처리방침이 적용됩니다."),
     ("아동", "Threes는 만 13세 미만 아동을 대상으로 하지 않으며, 위와 같이 누구의 개인정보도 수집하지 않습니다."),
     ("변경", "이 방침이 바뀌면 새 시행일과 함께 이 페이지에 게시합니다."),
     ("문의", f"개인정보 관련 문의는 {ISSUES} 에 이슈로 남겨 주세요.")],
    ""),
"ja": C("Threes サポート", "3秒のクリップを3つ、縦につないだ動画日記。",
    [("どうやって撮りますか？", "録画ボタンを押すと3秒で自動的に止まります。3回撮れば3カットの完成。アルバムの動画や写真を読み込むこともできます。"),
     ("完成した動画はどこにありますか？", "完成画面で「動画を保存」を押すと、透かしのない9:16のmp4として写真アプリに保存されます。クリップはお使いの端末の中にだけ保存されます。"),
     ("作業中の3カットはどのくらい残りますか？", "無料版は3件まで14日間、Proは件数無制限で90日間です。完成した3カットは7日間、再編集できます。"),
     ("Proの内容と復元方法は？", "Threes ProはAppleを通じた買い切りです。自分だけのラベル（テンプレート16種はもともと全部無料）、フィルター8種と強さ調整、作業中3カット無制限が使えます。別の端末では同じApple IDでサインインし、設定 → 購入を復元を押してください。"),
     ("自分のフォントは使えますか？", "はい。設定 → マイフォント、または編集画面のフォントタブ末尾の「+」カードから ttf・otf ファイルを追加できます。"),
     ("データを削除するには？", "ホームで3カットを削除するか、アプリを削除してください。データはすべて端末内にあるので、他の場所には何も残りません。")],
    "お問い合わせ", "不具合や質問は Issue にお書きください。そこでお返事します。", "GitHubでIssueを作成",
    "プライバシーポリシー", "サポート",
    "プライバシーポリシー", f"施行日 {EFFECTIVE}",
    [("要約", "Threesにはアカウントも独自サーバーもありません。撮影したものはすべて端末内に残り、個人情報は収集しません。"),
     ("カメラと写真", "クリップの撮影にカメラの許可を、完成した動画の保存に写真への追加の許可を求めます。どこにもアップロードしません。"),
     ("端末内のデータ", "クリップ、サムネイル、作業中の3カット、追加したフォント、設定は端末内にのみ保存されます。アプリ内で削除するか、アプリを削除すると消えます。"),
     ("購入", "Threes ProはAppleのアプリ内課金で販売しています。決済はAppleが処理し、決済情報やApple IDは当方に渡りません。購入の復元もAppleを通じて行われます。"),
     ("ネットワークの利用", "アプリがインターネットに接続するのは、新しいバージョンの確認時だけです。AppleのApp Storeにアプリの識別子とストアの地域で最新バージョンを問い合わせ、当方のホスティングから小さな更新案内ファイルを取得することがあります。また、アプリの使われ方を数えるためにGoogle Analytics for Firebaseを使用します。どの画面を開いたか、どのテンプレート・フィルターを選んだか、3カットを完成したか、購入したかがGoogleに送信され、ランダムなアプリインスタンスID・端末モデル・OSバージョン・言語・おおよその地域が一緒に含まれます。動画・写真・ラベルの内容やアカウント（ありません）は決して含まれません。広告識別子は使わず、広告やアプリ間トラッキングもありません。"),
     ("共有", "動画を共有すると、選択したアプリに渡され、そのアプリのプライバシーポリシーが適用されます。"),
     ("子ども", "Threesは13歳未満の子どもを対象としておらず、上記のとおり誰の個人情報も収集しません。"),
     ("変更", "本ポリシーを変更する場合は、新しい施行日とともにこのページに掲載します。"),
     ("お問い合わせ", f"プライバシーに関するご質問は {ISSUES} にIssueをお書きください。")],
    ""),
"zh-Hans": C("Threes 支持", "三段 3 秒短片，竖向拼成一支视频日记。",
    [("怎么拍？", "按下录制按钮，3 秒后自动停止。拍三次，三格就完成了。也可以从相册导入视频或照片。"),
     ("完成的视频在哪里？", "在完成页面点“保存视频”，会以无水印的 9:16 mp4 保存到照片 App。片段只保存在你的手机里。"),
     ("草稿能保留多久？", "免费版最多 3 个草稿、保留 14 天；Pro 不限数量、保留 90 天。完成的三格 7 天内可以重新编辑。"),
     ("Pro 包含什么？怎么恢复购买？", "Threes Pro 通过 Apple 一次性购买：自定义标签（16 个模板本来就全部免费）、另外 8 款滤镜和强度调节、草稿不限量。换设备时，用同一个 Apple ID 登录，然后在设置 → 恢复购买。"),
     ("能用自己的字体吗？", "可以。在设置 → 我的字体，或编辑页字体标签末尾的“+”卡片添加 ttf/otf 文件。"),
     ("怎么删除我的数据？", "在首页删除三格，或直接删除 App。所有数据都只在你的设备上，别处不会留下任何东西。")],
    "联系我们", "有问题或发现 bug，请提交 issue，我们会在那里回复。", "在 GitHub 提交 issue",
    "隐私政策", "支持",
    "隐私政策", f"生效日期 {EFFECTIVE}",
    [("简要说明", "Threes 没有账号，也没有自己的服务器。你拍的一切都留在设备上，我们不收集个人数据。"),
     ("相机与照片", "拍摄片段需要相机权限，保存成片需要“添加到照片”权限。任何内容都不会被上传。"),
     ("设备上的数据", "片段、缩略图、草稿、你添加的字体和设置只保存在你的设备上。你在 App 内删除或卸载 App 后即被移除。"),
     ("购买", "Threes Pro 通过 Apple 的 App 内购买销售。付款由 Apple 处理，我们不会看到你的付款信息或 Apple ID。恢复购买同样通过 Apple 完成。"),
     ("网络使用", "App 只在检查新版本时联网：向 Apple App Store 查询本 App 的标识符和你所在的商店地区，并可能从我们的托管服务获取一个小的更新提示文件。此外，App 使用 Google Analytics for Firebase 统计使用情况：打开了哪些界面、选了哪些模板和滤镜、是否完成三格、是否购买。这些会连同随机的 App 实例 ID、设备型号、系统版本、语言和大致地区一起发送给 Google。绝不包含你的视频、照片、标签内容或账户（本来就没有）。不使用广告标识符，也没有广告或跨 App 跟踪。"),
     ("分享", "分享视频时，视频会交给你选择的 App，并适用该 App 的隐私政策。"),
     ("儿童", "Threes 不面向 13 岁以下儿童，且如上所述不收集任何人的个人数据。"),
     ("变更", "如本政策有变更，将在本页面发布新版本并更新生效日期。"),
     ("联系", f"隐私相关问题请在 {ISSUES} 提交 issue。")],
    ""),
"zh-Hant": C("Threes 支援", "三段 3 秒短片，直向接成一支影片日記。",
    [("怎麼拍？", "按下錄製按鈕，3 秒後自動停止。拍三次，三格就完成了。也可以從相簿匯入影片或照片。"),
     ("完成的影片在哪裡？", "在完成頁面點「儲存影片」，會以無浮水印的 9:16 mp4 儲存到照片 App。片段只保存在你的手機裡。"),
     ("草稿能保留多久？", "免費版最多 3 個草稿、保留 14 天；Pro 不限數量、保留 90 天。完成的三格 7 天內可以重新編輯。"),
     ("Pro 包含什麼？怎麼回復購買？", "Threes Pro 透過 Apple 一次性購買：自訂標籤（16 個範本本來就全部免費）、另外 8 款濾鏡和強度調整、草稿不限量。換裝置時，用同一個 Apple ID 登入，然後在設定 → 回復購買。"),
     ("能用自己的字體嗎？", "可以。在設定 → 我的字體，或編輯頁字體標籤末尾的「+」卡片加入 ttf/otf 檔案。"),
     ("怎麼刪除我的資料？", "在首頁刪除三格，或直接刪除 App。所有資料都只在你的裝置上，別處不會留下任何東西。")],
    "聯絡我們", "有問題或發現 bug，請建立 issue，我們會在那裡回覆。", "在 GitHub 建立 issue",
    "隱私權政策", "支援",
    "隱私權政策", f"生效日期 {EFFECTIVE}",
    [("簡要說明", "Threes 沒有帳號，也沒有自己的伺服器。你拍的一切都留在裝置上，我們不蒐集個人資料。"),
     ("相機與照片", "拍攝片段需要相機權限，儲存成品需要「加入照片」權限。任何內容都不會被上傳。"),
     ("裝置上的資料", "片段、縮圖、草稿、你加入的字體和設定只保存在你的裝置上。你在 App 內刪除或移除 App 後即被清除。"),
     ("購買", "Threes Pro 透過 Apple 的 App 內購買販售。付款由 Apple 處理，我們不會看到你的付款資訊或 Apple ID。回復購買同樣透過 Apple 完成。"),
     ("網路使用", "App 只在檢查新版本時連網：向 Apple App Store 查詢本 App 的識別碼和你所在的商店地區，並可能從我們的主機取得一個小的更新提示檔案。此外，App 使用 Google Analytics for Firebase 統計使用情況：開了哪些畫面、選了哪些範本和濾鏡、是否完成三格、是否購買。這些會連同隨機的 App 實例 ID、裝置型號、系統版本、語言和大致地區一起傳送給 Google。絕不包含你的影片、照片、標籤內容或帳號（本來就沒有）。不使用廣告識別碼，也沒有廣告或跨 App 追蹤。"),
     ("分享", "分享影片時，影片會交給你選擇的 App，並適用該 App 的隱私權政策。"),
     ("兒童", "Threes 不以 13 歲以下兒童為對象，且如上所述不蒐集任何人的個人資料。"),
     ("變更", "如本政策有變更，將在本頁面發布新版本並更新生效日期。"),
     ("聯絡", f"隱私相關問題請在 {ISSUES} 建立 issue。")],
    ""),
"vi": C("Hỗ trợ Threes", "Ba clip 3 giây, xếp dọc thành một video nhật ký.",
    [("Quay như thế nào?", "Chạm nút quay, máy tự dừng sau 3 giây. Quay ba lần là xong bộ 3 cảnh. Bạn cũng có thể lấy video hoặc ảnh từ album."),
     ("Video của tôi ở đâu?", "Ở màn hình hoàn thành, chạm Lưu video: video 9:16 mp4 không watermark sẽ vào ứng dụng Ảnh. Clip chỉ được lưu trên điện thoại của bạn."),
     ("Bản nháp giữ được bao lâu?", "Bản miễn phí giữ tối đa 3 bản nháp trong 14 ngày. Pro không giới hạn, giữ 90 ngày. Bộ 3 cảnh đã hoàn thành có thể sửa lại trong 7 ngày."),
     ("Pro gồm những gì và khôi phục ra sao?", "Threes Pro là mua một lần qua Apple: nhãn tùy chỉnh (cả 16 mẫu vốn đã miễn phí), thêm 8 bộ lọc kèm chỉnh độ mạnh, bản nháp không giới hạn. Trên thiết bị khác, đăng nhập cùng Apple ID rồi vào Cài đặt → Khôi phục mua hàng."),
     ("Dùng phông chữ riêng được không?", "Được. Thêm tệp ttf hoặc otf trong Cài đặt → Phông chữ của tôi, hoặc thẻ + ở cuối tab Phông chữ khi chỉnh sửa."),
     ("Xóa dữ liệu của tôi thế nào?", "Xóa bộ 3 cảnh ở trang chủ, hoặc xóa ứng dụng. Mọi thứ nằm trên thiết bị của bạn nên không còn gì ở nơi khác.")],
    "Liên hệ", "Gặp lỗi hoặc có câu hỏi? Hãy mở một issue, chúng tôi sẽ trả lời ở đó.", "Mở issue trên GitHub",
    "Chính sách quyền riêng tư", "Hỗ trợ",
    "Chính sách quyền riêng tư", f"Có hiệu lực từ {EFFECTIVE}",
    [("Tóm tắt", "Threes không có tài khoản và không có máy chủ riêng. Mọi thứ bạn quay đều ở trên thiết bị. Chúng tôi không thu thập dữ liệu cá nhân."),
     ("Camera và Ảnh", "Threes xin quyền camera để quay clip và quyền thêm vào Ảnh để lưu video hoàn thành. Không có gì được tải lên đâu cả."),
     ("Dữ liệu trên thiết bị", "Clip, ảnh thu nhỏ, bản nháp, phông chữ bạn thêm và cài đặt chỉ được lưu trên thiết bị. Chúng bị xóa khi bạn xóa trong ứng dụng hoặc gỡ ứng dụng."),
     ("Mua hàng", "Threes Pro được bán qua Mua trong ứng dụng của Apple. Apple xử lý thanh toán; chúng tôi không thấy thông tin thanh toán hay Apple ID của bạn. Khôi phục mua hàng cũng qua Apple."),
     ("Sử dụng mạng", "Ứng dụng chỉ kết nối internet để kiểm tra phiên bản mới: hỏi App Store của Apple bằng mã định danh của ứng dụng và khu vực cửa hàng của bạn, và có thể tải một tệp thông báo cập nhật nhỏ từ máy chủ lưu trữ của chúng tôi. Ứng dụng cũng dùng Google Analytics for Firebase để đếm cách ứng dụng được sử dụng: màn hình nào được mở, mẫu và bộ lọc nào được chọn, có hoàn thành ba cảnh hay mua hàng không. Dữ liệu này được gửi tới Google cùng một ID phiên bản ứng dụng ngẫu nhiên, kiểu máy, phiên bản hệ điều hành, ngôn ngữ và khu vực đại khái. Không bao giờ gồm video, ảnh, nội dung nhãn hay tài khoản của bạn (vốn không có). Không dùng mã định danh quảng cáo, không quảng cáo, không theo dõi giữa các ứng dụng."),
     ("Chia sẻ", "Khi bạn chia sẻ video, video được chuyển cho ứng dụng bạn chọn và chính sách của ứng dụng đó sẽ áp dụng."),
     ("Trẻ em", "Threes không hướng đến trẻ em dưới 13 tuổi và, như đã nêu, không thu thập dữ liệu cá nhân của bất kỳ ai."),
     ("Thay đổi", "Nếu chính sách này thay đổi, phiên bản mới sẽ được đăng tại trang này với ngày hiệu lực mới."),
     ("Liên hệ", f"Câu hỏi về quyền riêng tư: mở issue tại {ISSUES}.")],
    ""),
"es": C("Soporte de Threes", "Tres clips de 3 segundos, apilados en un diario en video vertical.",
    [("¿Cómo grabo?", "Toca el botón de grabar. Graba 3 segundos y se detiene solo. Hazlo tres veces y tus 3 tomas están listas. También puedes traer un video o una foto de tu álbum."),
     ("¿Dónde están mis videos?", "En la pantalla final toca Guardar video y se guarda en Fotos como mp4 9:16 sin marca de agua. Los clips solo se guardan en tu teléfono."),
     ("¿Cuánto tiempo se guardan los borradores?", "La versión gratis guarda hasta 3 borradores durante 14 días. Pro guarda borradores ilimitados durante 90 días. Unas 3 tomas terminadas se pueden volver a editar durante 7 días."),
     ("¿Qué incluye Pro y cómo lo restauro?", "Threes Pro es una compra única a través de Apple: etiquetas propias (las 16 plantillas ya son gratis), 8 filtros más con intensidad y borradores ilimitados. En otro dispositivo, inicia sesión con el mismo Apple ID y toca Ajustes → Restaurar compras."),
     ("¿Puedo usar mi propia fuente?", "Sí. Añade un archivo ttf u otf en Ajustes → Mis fuentes, o con la tarjeta + al final de la pestaña Fuente al editar."),
     ("¿Cómo borro mis datos?", "Elimina unas 3 tomas desde Inicio o elimina la app. Todo vive en tu dispositivo, así que no queda nada en ningún otro sitio.")],
    "Contacto", "¿Un error o una duda? Abre un issue y te respondemos ahí.", "Abrir un issue en GitHub",
    "Política de privacidad", "Soporte",
    "Política de privacidad", f"Vigente desde el {EFFECTIVE}",
    [("En resumen", "Threes no tiene cuenta ni servidor propio. Todo lo que grabas se queda en tu dispositivo. No recopilamos datos personales."),
     ("Cámara y Fotos", "Threes pide la cámara para grabar tus clips y permiso para añadir a Fotos para guardar el video terminado. No se sube nada a ningún sitio."),
     ("Datos en tu dispositivo", "Los clips, miniaturas, borradores, fuentes que añades y ajustes se guardan solo en tu dispositivo. Se eliminan cuando los borras en la app o eliminas la app."),
     ("Compras", "Threes Pro se vende mediante la compra dentro de la app de Apple. Apple gestiona el pago; nunca vemos tus datos de pago ni tu Apple ID. Restaurar una compra también pasa por Apple."),
     ("Uso de red", "La app se conecta a internet solo para comprobar si hay una versión nueva: consulta al App Store de Apple con el identificador de la app y tu región de tienda, y puede descargar un pequeño archivo de aviso de actualización desde nuestro alojamiento. La app también usa Google Analytics for Firebase para contar cómo se usa: qué pantallas se abren, qué plantillas y filtros se eligen, si se termina un tres o se hace una compra. Esto se envía a Google junto con un ID aleatorio de instancia de la app, el modelo del dispositivo, la versión del sistema, el idioma y la región aproximada. Nunca incluye tus vídeos, fotos, etiquetas ni ninguna cuenta (no la hay). No se usa el identificador de publicidad y no hay publicidad ni rastreo entre apps."),
     ("Compartir", "Cuando compartes un video, se entrega a la app que elijas y se aplica la política de privacidad de esa app."),
     ("Menores", "Threes no está dirigida a menores de 13 años y, como se indica arriba, no recopila datos personales de nadie."),
     ("Cambios", "Si esta política cambia, la nueva versión se publicará en esta página con una nueva fecha de vigencia."),
     ("Contacto", f"Preguntas sobre privacidad: abre un issue en {ISSUES}.")],
    ""),
"pt-BR": C("Suporte do Threes", "Três clipes de 3 segundos, empilhados em um diário em vídeo vertical.",
    [("Como eu gravo?", "Toque no botão de gravar. Ele grava 3 segundos e para sozinho. Faça isso três vezes e suas 3 cenas estão prontas. Você também pode puxar um vídeo ou foto do seu álbum."),
     ("Onde estão meus vídeos?", "Na tela final, toque em Salvar vídeo e ele vai para o app Fotos como mp4 9:16 sem marca d'água. Os clipes ficam só no seu celular."),
     ("Por quanto tempo os rascunhos ficam guardados?", "A versão grátis guarda até 3 rascunhos por 14 dias. O Pro guarda rascunhos ilimitados por 90 dias. Uma cena tripla concluída pode ser reeditada por 7 dias."),
     ("O que o Pro inclui e como restauro?", "O Threes Pro é uma compra única pela Apple: textos personalizados (os 16 modelos já são grátis), mais 8 filtros com intensidade e rascunhos ilimitados. Em outro aparelho, entre com o mesmo Apple ID e toque em Ajustes → Restaurar compras."),
     ("Posso usar minha própria fonte?", "Sim. Adicione um arquivo ttf ou otf em Ajustes → Minhas fontes, ou pelo cartão + no fim da aba Fonte ao editar."),
     ("Como apago meus dados?", "Exclua as 3 cenas no Início ou exclua o app. Tudo fica no seu aparelho, então não sobra nada em outro lugar.")],
    "Contato", "Achou um bug ou tem uma dúvida? Abra um issue e respondemos por lá.", "Abrir um issue no GitHub",
    "Política de privacidade", "Suporte",
    "Política de privacidade", f"Em vigor desde {EFFECTIVE}",
    [("Resumo", "O Threes não tem conta nem servidor próprio. Tudo o que você grava fica no seu aparelho. Não coletamos dados pessoais."),
     ("Câmera e Fotos", "O Threes pede a câmera para gravar seus clipes e permissão para adicionar a Fotos para salvar o vídeo pronto. Nada é enviado para lugar nenhum."),
     ("Dados no seu aparelho", "Clipes, miniaturas, rascunhos, fontes que você adiciona e ajustes ficam só no seu aparelho. São removidos quando você os exclui no app ou exclui o app."),
     ("Compras", "O Threes Pro é vendido pela compra no app da Apple. A Apple processa o pagamento; nunca vemos seus dados de pagamento nem seu Apple ID. Restaurar uma compra também passa pela Apple."),
     ("Uso de rede", "O app se conecta à internet só para verificar se há uma versão nova: consulta a App Store da Apple com o identificador do app e sua região de loja, e pode baixar um pequeno arquivo de aviso de atualização da nossa hospedagem. O app também usa o Google Analytics for Firebase para contar como ele é usado: quais telas abrem, quais modelos e filtros são escolhidos, se um três é concluído ou uma compra é feita. Isso vai para o Google junto com um ID aleatório de instância do app, modelo do aparelho, versão do sistema, idioma e região aproximada. Nunca inclui seus vídeos, fotos, etiquetas nem conta alguma (não existe). Não usa o identificador de publicidade e não há publicidade nem rastreamento entre apps."),
     ("Compartilhamento", "Quando você compartilha um vídeo, ele é entregue ao app que você escolher, e a política de privacidade desse app se aplica."),
     ("Crianças", "O Threes não é dirigido a menores de 13 anos e, como descrito acima, não coleta dados pessoais de ninguém."),
     ("Alterações", "Se esta política mudar, a nova versão será publicada nesta página com uma nova data de vigência."),
     ("Contato", f"Dúvidas sobre privacidade: abra um issue em {ISSUES}.")],
    ""),
"th": C("ฝ่ายสนับสนุน Threes", "3 คลิป คลิปละ 3 วินาที ต่อกันแนวตั้งเป็นวิดีโอไดอารี่",
    [("ถ่ายอย่างไร?", "แตะปุ่มถ่าย เครื่องจะถ่าย 3 วินาทีแล้วหยุดเอง ถ่าย 3 ครั้งก็ครบชุด หรือจะนำเข้าวิดีโอและรูปจากอัลบั้มก็ได้"),
     ("วิดีโอของฉันอยู่ที่ไหน?", "ที่หน้าเสร็จสิ้น แตะ “บันทึกวิดีโอ” ไฟล์ mp4 9:16 ไม่มีลายน้ำจะเข้าไปในแอปรูปภาพ คลิปถูกเก็บไว้ในเครื่องของคุณเท่านั้น"),
     ("ฉบับร่างเก็บได้นานแค่ไหน?", "แบบฟรีเก็บได้ 3 ชุด นาน 14 วัน Pro เก็บได้ไม่จำกัด นาน 90 วัน ชุดที่เสร็จแล้วแก้ไขซ้ำได้ภายใน 7 วัน"),
     ("Pro มีอะไรบ้าง และกู้คืนอย่างไร?", "Threes Pro เป็นการซื้อครั้งเดียวผ่าน Apple: ป้ายกำหนดเอง (เทมเพลตทั้ง 16 แบบฟรีอยู่แล้ว) ฟิลเตอร์เพิ่มอีก 8 แบบพร้อมปรับความแรง และฉบับร่างไม่จำกัด บนเครื่องอื่น ให้ลงชื่อเข้าใช้ Apple ID เดิมแล้วไปที่ การตั้งค่า → กู้คืนการซื้อ"),
     ("ใช้ฟอนต์ของตัวเองได้ไหม?", "ได้ เพิ่มไฟล์ ttf หรือ otf ที่ การตั้งค่า → ฟอนต์ของฉัน หรือการ์ด + ท้ายแท็บฟอนต์ตอนแก้ไข"),
     ("ลบข้อมูลของฉันอย่างไร?", "ลบชุดคลิปที่หน้าแรก หรือลบแอป ข้อมูลทั้งหมดอยู่ในเครื่องของคุณ จึงไม่มีอะไรเหลืออยู่ที่อื่น")],
    "ติดต่อ", "พบบั๊กหรือมีคำถาม? เปิด issue ไว้ได้เลย เราจะตอบที่นั่น", "เปิด issue บน GitHub",
    "นโยบายความเป็นส่วนตัว", "ฝ่ายสนับสนุน",
    "นโยบายความเป็นส่วนตัว", f"มีผลตั้งแต่ {EFFECTIVE}",
    [("สรุป", "Threes ไม่มีบัญชีผู้ใช้และไม่มีเซิร์ฟเวอร์ของตัวเอง ทุกอย่างที่คุณถ่ายอยู่ในเครื่องของคุณ เราไม่เก็บข้อมูลส่วนบุคคล"),
     ("กล้องและรูปภาพ", "Threes ขอสิทธิ์กล้องเพื่อถ่ายคลิป และสิทธิ์เพิ่มลงรูปภาพเพื่อบันทึกวิดีโอที่เสร็จแล้ว ไม่มีการอัปโหลดไปที่ใด"),
     ("ข้อมูลในเครื่อง", "คลิป ภาพย่อ ฉบับร่าง ฟอนต์ที่คุณเพิ่ม และการตั้งค่า ถูกเก็บไว้ในเครื่องเท่านั้น และจะหายไปเมื่อคุณลบในแอปหรือลบแอป"),
     ("การซื้อ", "Threes Pro ขายผ่านการซื้อภายในแอปของ Apple โดย Apple เป็นผู้จัดการการชำระเงิน เราไม่เห็นข้อมูลการชำระเงินหรือ Apple ID ของคุณ การกู้คืนการซื้อก็ผ่าน Apple เช่นกัน"),
     ("การใช้เครือข่าย", "แอปเชื่อมต่ออินเทอร์เน็ตเฉพาะตอนตรวจสอบเวอร์ชันใหม่ โดยสอบถาม App Store ของ Apple ด้วยตัวระบุของแอปและภูมิภาคของสโตร์ และอาจดึงไฟล์แจ้งเตือนอัปเดตขนาดเล็กจากโฮสติ้งของเรา แอปยังใช้ Google Analytics for Firebase เพื่อนับว่าแอปถูกใช้อย่างไร เช่น เปิดหน้าไหน เลือกเทมเพลตและฟิลเตอร์ใด ทำสามคลิปเสร็จหรือซื้อหรือไม่ ข้อมูลนี้ส่งไป Google พร้อม ID อินสแตนซ์ของแอปแบบสุ่ม รุ่นอุปกรณ์ เวอร์ชันระบบ ภาษา และภูมิภาคโดยประมาณ ไม่มีวิดีโอ รูปภาพ ข้อความป้าย หรือบัญชีของคุณ (ซึ่งไม่มีอยู่แล้ว) รวมอยู่เด็ดขาด ไม่ใช้ตัวระบุโฆษณา ไม่มีโฆษณา และไม่มีการติดตามข้ามแอป"),
     ("การแชร์", "เมื่อคุณแชร์วิดีโอ วิดีโอจะถูกส่งให้แอปที่คุณเลือก และนโยบายความเป็นส่วนตัวของแอปนั้นจะมีผล"),
     ("เด็ก", "Threes ไม่ได้มุ่งเป้าไปที่เด็กอายุต่ำกว่า 13 ปี และดังที่กล่าวข้างต้น ไม่เก็บข้อมูลส่วนบุคคลของใครทั้งสิ้น"),
     ("การเปลี่ยนแปลง", "หากนโยบายนี้เปลี่ยน เวอร์ชันใหม่จะถูกโพสต์ในหน้านี้พร้อมวันที่มีผลใหม่"),
     ("ติดต่อ", f"คำถามเรื่องความเป็นส่วนตัว: เปิด issue ได้ที่ {ISSUES}")],
    ""),
"id": C("Dukungan Threes", "Tiga klip 3 detik, ditumpuk jadi satu diary video vertikal.",
    [("Bagaimana cara merekam?", "Ketuk tombol rekam. Aplikasi merekam 3 detik lalu berhenti sendiri. Lakukan tiga kali dan 3 klipmu selesai. Kamu juga bisa mengambil video atau foto dari album."),
     ("Di mana video saya?", "Di layar selesai, ketuk Simpan video dan video masuk ke aplikasi Foto sebagai mp4 9:16 tanpa watermark. Klip hanya tersimpan di ponselmu."),
     ("Berapa lama draf disimpan?", "Versi gratis menyimpan maksimal 3 draf selama 14 hari. Pro menyimpan draf tanpa batas selama 90 hari. 3 klip yang selesai bisa diedit ulang selama 7 hari."),
     ("Apa isi Pro dan cara memulihkannya?", "Threes Pro adalah pembelian sekali lewat Apple: label kustom (semua 16 templat memang sudah gratis), 8 filter tambahan dengan pengaturan kekuatan, dan draf tanpa batas. Di perangkat lain, masuk dengan Apple ID yang sama lalu ketuk Pengaturan → Pulihkan pembelian."),
     ("Bisa pakai font sendiri?", "Bisa. Tambahkan file ttf atau otf di Pengaturan → Font saya, atau lewat kartu + di ujung tab Font saat mengedit."),
     ("Bagaimana cara menghapus data saya?", "Hapus 3 klip dari Beranda, atau hapus aplikasinya. Semua ada di perangkatmu, jadi tidak ada yang tersisa di tempat lain.")],
    "Kontak", "Menemukan bug atau punya pertanyaan? Buka issue, kami balas di sana.", "Buka issue di GitHub",
    "Kebijakan Privasi", "Dukungan",
    "Kebijakan Privasi", f"Berlaku sejak {EFFECTIVE}",
    [("Singkatnya", "Threes tidak punya akun dan tidak punya server sendiri. Semua yang kamu rekam tetap di perangkatmu. Kami tidak mengumpulkan data pribadi."),
     ("Kamera dan Foto", "Threes meminta akses kamera untuk merekam klip dan izin menambahkan ke Foto untuk menyimpan video yang selesai. Tidak ada yang diunggah ke mana pun."),
     ("Data di perangkatmu", "Klip, thumbnail, draf, font yang kamu tambahkan, dan pengaturan hanya tersimpan di perangkatmu. Semuanya terhapus saat kamu menghapusnya di aplikasi atau menghapus aplikasi."),
     ("Pembelian", "Threes Pro dijual lewat Pembelian Dalam Aplikasi Apple. Apple yang memproses pembayaran; kami tidak pernah melihat data pembayaran atau Apple ID-mu. Pemulihan pembelian juga lewat Apple."),
     ("Penggunaan jaringan", "Aplikasi terhubung ke internet hanya untuk memeriksa versi baru: menanyakan App Store Apple dengan pengenal aplikasi dan wilayah toko-mu, dan mungkin mengambil file pemberitahuan pembaruan kecil dari hosting kami. Aplikasi juga memakai Google Analytics for Firebase untuk menghitung cara aplikasi dipakai: layar mana yang dibuka, templat dan filter mana yang dipilih, apakah tiga klip selesai atau pembelian terjadi. Ini dikirim ke Google bersama ID instans aplikasi acak, model perangkat, versi sistem, bahasa, dan wilayah perkiraan. Tidak pernah menyertakan video, foto, isi label, atau akunmu (memang tidak ada). Tidak memakai pengenal iklan, tidak ada iklan, dan tidak ada pelacakan lintas aplikasi."),
     ("Berbagi", "Saat kamu membagikan video, video diserahkan ke aplikasi yang kamu pilih, dan kebijakan privasi aplikasi itu yang berlaku."),
     ("Anak-anak", "Threes tidak ditujukan untuk anak di bawah 13 tahun dan, seperti dijelaskan di atas, tidak mengumpulkan data pribadi siapa pun."),
     ("Perubahan", "Jika kebijakan ini berubah, versi baru akan dipasang di halaman ini dengan tanggal berlaku baru."),
     ("Kontak", f"Pertanyaan tentang privasi: buka issue di {ISSUES}.")],
    ""),
"de": C("Threes Support", "Drei 3-Sekunden-Clips, gestapelt zu einem vertikalen Video-Tagebuch.",
    [("Wie nehme ich auf?", "Tipp auf den Aufnahmeknopf. Es werden 3 Sekunden aufgenommen, dann stoppt die Aufnahme von selbst. Dreimal machen und dein 3er-Video ist fertig. Du kannst auch ein Video oder Foto aus dem Album holen."),
     ("Wo sind meine Videos?", "Tipp auf dem fertigen Bildschirm auf „Video speichern“, dann landet es als 9:16-mp4 ohne Wasserzeichen in der Fotos-App. Clips werden nur auf deinem Handy gespeichert."),
     ("Wie lange bleiben Entwürfe?", "Gratis behält bis zu 3 Entwürfe für 14 Tage. Pro behält unbegrenzt Entwürfe für 90 Tage. Ein fertiges 3er-Video kannst du 7 Tage lang noch mal bearbeiten."),
     ("Was ist in Pro drin, und wie stelle ich es wieder her?", "Threes Pro ist ein Einmalkauf über Apple: eigene Labels (alle 16 Vorlagen sind schon gratis), 8 Filter mehr mit Stärkeregler, unbegrenzt Entwürfe. Auf einem anderen Gerät meldest du dich mit derselben Apple-ID an und tippst auf Einstellungen → Käufe wiederherstellen."),
     ("Kann ich meine eigene Schrift nutzen?", "Ja. Füg eine ttf- oder otf-Datei unter Einstellungen → Meine Schriften hinzu, oder über die +-Karte am Ende des Schrift-Tabs beim Bearbeiten."),
     ("Wie lösche ich meine Daten?", "Lösch ein 3er-Video auf dem Startbildschirm oder lösch die App. Alles liegt auf deinem Gerät, woanders bleibt also nichts zurück.")],
    "Kontakt", "Bug gefunden oder eine Frage? Mach ein Issue auf, wir antworten dort.", "Issue auf GitHub öffnen",
    "Datenschutz", "Support",
    "Datenschutzerklärung", f"Gültig ab {EFFECTIVE}",
    [("Kurz gesagt", "Threes hat kein Konto und keinen eigenen Server. Alles, was du aufnimmst, bleibt auf deinem Gerät. Wir sammeln keine personenbezogenen Daten; das Einzige, was dein Handy verlässt, sind anonyme Nutzungsstatistiken (siehe Netzwerknutzung)."),
     ("Kamera und Fotos", "Threes fragt nach der Kamera, um deine Clips aufzunehmen, und nach der Berechtigung, zu Fotos hinzuzufügen, um dein fertiges Video zu speichern. Nichts wird irgendwohin hochgeladen."),
     ("Daten auf deinem Gerät", "Clips, Vorschaubilder, Entwürfe, hinzugefügte Schriften und deine Einstellungen werden nur auf deinem Gerät gespeichert. Sie werden entfernt, wenn du sie in der App löschst oder die App löschst."),
     ("Käufe", "Threes Pro wird über Apples In-App-Kauf verkauft. Apple wickelt die Zahlung ab; wir sehen weder deine Zahlungsdaten noch deine Apple-ID. Auch das Wiederherstellen eines Kaufs läuft über Apple."),
     ("Netzwerknutzung", "Die App geht nur ins Internet, um zu prüfen, ob eine neuere Version existiert: Sie fragt Apples App Store nach der eigenen App-Kennung und deiner Store-Region und lädt eventuell eine kleine Update-Hinweisdatei von unserem Hosting. Es werden keine Gerätekennungen gesendet. Threes nutzt außerdem Google Analytics for Firebase, um zu zählen, wie die App genutzt wird: welche Bildschirme geöffnet, welche Vorlagen und Filter gewählt werden, ob ein 3er-Video fertiggestellt oder ein Kauf gemacht wird. Dabei gehen eine zufällige App-Instanz-ID, Gerätemodell, OS-Version, Sprache und ungefähre Region an Google. Nie enthalten sind deine Videos, Fotos, Labels oder ein Konto – es gibt keins. Es wird keine Werbe-ID verwendet, und es gibt keine Werbung und kein App-übergreifendes Tracking."),
     ("Teilen", "Wenn du ein Video teilst, wird es an die App übergeben, die du auswählst, und es gilt die Datenschutzerklärung dieser App."),
     ("Kinder", "Threes richtet sich nicht an Kinder unter 13 Jahren und sammelt, wie oben beschrieben, von niemandem personenbezogene Daten."),
     ("Änderungen", "Wenn sich diese Erklärung ändert, wird die neue Fassung mit neuem Gültigkeitsdatum auf dieser Seite veröffentlicht."),
     ("Kontakt", f"Fragen zum Datenschutz: Mach ein Issue auf unter {ISSUES}.")],
    ""),
"fr": C("Assistance Threes", "Trois clips de 3 secondes, empilés en un journal vidéo vertical.",
    [("Comment filmer ?", "Touche le bouton d'enregistrement. Ça filme 3 secondes et s'arrête tout seul. Fais-le trois fois et ton trio est prêt. Tu peux aussi importer une vidéo ou une photo depuis ton album."),
     ("Où sont mes vidéos ?", "Touche Enregistrer la vidéo sur l'écran final : elle part dans l'app Photos en mp4 9:16, sans filigrane. Les clips ne sont stockés que sur ton téléphone."),
     ("Combien de temps les brouillons sont-ils gardés ?", "En gratuit, jusqu'à 3 brouillons pendant 14 jours. Avec Pro, brouillons illimités pendant 90 jours. Un trio terminé peut être remodifié pendant 7 jours."),
     ("Que contient Pro, et comment le restaurer ?", "Threes Pro est un achat unique via Apple : labels perso (les 16 modèles sont déjà gratuits), 8 filtres en plus avec réglage d'intensité, brouillons illimités. Pour le restaurer sur un autre appareil, connecte-toi avec le même identifiant Apple et touche Réglages → Restaurer les achats."),
     ("Je peux utiliser ma propre police ?", "Oui. Ajoute un fichier ttf ou otf dans Réglages → Mes polices, ou avec la carte + à la fin de l'onglet Police pendant l'édition."),
     ("Comment supprimer mes données ?", "Supprime un trio depuis l'accueil, ou supprime l'app. Tout vit sur ton appareil, donc il ne reste rien ailleurs.")],
    "Contact", "Un bug ou une question ? Ouvre un ticket et on te répond là-bas.", "Ouvrir un ticket sur GitHub",
    "Politique de confidentialité", "Assistance",
    "Politique de confidentialité", f"En vigueur depuis le {EFFECTIVE}",
    [("En bref", "Threes n'a ni compte ni serveur à lui. Tout ce que tu filmes reste sur ton appareil. Nous ne collectons aucune donnée personnelle ; la seule chose qui quitte ton téléphone, ce sont des statistiques d'utilisation anonymes (voir Utilisation du réseau)."),
     ("Caméra et Photos", "Threes demande l'accès à la caméra pour filmer tes clips, et l'autorisation d'ajouter à Photos pour enregistrer ta vidéo terminée. Rien n'est envoyé nulle part."),
     ("Données sur ton appareil", "Les clips, miniatures, brouillons, polices ajoutées et tes réglages sont stockés uniquement sur ton appareil. Ils disparaissent quand tu les supprimes dans l'app ou que tu supprimes l'app."),
     ("Achats", "Threes Pro est vendu via l'achat intégré d'Apple. Apple gère le paiement ; nous ne voyons jamais tes informations de paiement ni ton identifiant Apple. La restauration d'un achat passe aussi par Apple."),
     ("Utilisation du réseau", "L'app se connecte à internet uniquement pour vérifier s'il existe une version plus récente, en interrogeant l'App Store d'Apple avec l'identifiant de l'app et ta région de store, et éventuellement en récupérant un petit fichier d'avis de mise à jour sur notre hébergement. Aucun identifiant d'appareil n'est envoyé. Threes utilise aussi Google Analytics pour Firebase pour compter comment l'app est utilisée : quels écrans s'ouvrent, quels modèles et filtres sont choisis, si un trio est terminé ou un achat effectué. Cela envoie à Google un identifiant d'instance aléatoire, le modèle d'appareil, la version du système, la langue et une région approximative. Jamais tes vidéos, photos, labels ni un compte, puisqu'il n'y en a pas. Aucun identifiant publicitaire n'est utilisé, et il n'y a ni publicité ni suivi entre apps."),
     ("Partage", "Quand tu partages une vidéo, elle est transmise à l'app que tu choisis, et c'est la politique de confidentialité de cette app qui s'applique."),
     ("Enfants", "Threes ne s'adresse pas aux enfants de moins de 13 ans et, comme décrit ci-dessus, ne collecte de données personnelles auprès de personne."),
     ("Modifications", "Si cette politique change, la nouvelle version sera publiée sur cette page avec une nouvelle date d'entrée en vigueur."),
     ("Contact", f"Une question sur la confidentialité ? Ouvre un ticket sur {ISSUES}.")],
    ""),
"hi": C("Threes सपोर्ट", "3 सेकंड की तीन क्लिप, एक वर्टिकल वीडियो डायरी में।",
    [("रिकॉर्ड कैसे करें?", "रिकॉर्ड बटन टैप करें। 3 सेकंड रिकॉर्ड होकर खुद रुक जाता है। ऐसा तीन बार करें और आपकी थ्री तैयार। एल्बम से वीडियो या फ़ोटो भी ला सकते हैं।"),
     ("मेरे वीडियो कहाँ हैं?", "तैयार होने वाली स्क्रीन पर 'वीडियो सेव करें' टैप करें, यह बिना वॉटरमार्क के 9:16 mp4 बनकर Photos ऐप में चला जाता है। क्लिप सिर्फ़ आपके फ़ोन में रहती हैं।"),
     ("ड्राफ़्ट कब तक रहते हैं?", "फ़्री में 3 ड्राफ़्ट 14 दिन तक रहते हैं। Pro में अनलिमिटेड ड्राफ़्ट 90 दिन तक। तैयार थ्री को 7 दिन तक दोबारा एडिट कर सकते हैं।"),
     ("Pro में क्या मिलता है, और रीस्टोर कैसे करें?", "Threes Pro Apple के ज़रिए एक बार की खरीदारी है: कस्टम लेबल (सारे 16 टेम्पलेट पहले से फ़्री हैं), स्ट्रेंथ कंट्रोल के साथ 8 और फ़िल्टर, अनलिमिटेड ड्राफ़्ट। दूसरे डिवाइस पर रीस्टोर करने के लिए उसी Apple ID से साइन इन करें और सेटिंग्स → खरीदारी रीस्टोर करें टैप करें।"),
     ("क्या अपना फ़ॉन्ट लगा सकते हैं?", "हाँ। सेटिंग्स → मेरे फ़ॉन्ट में ttf या otf फ़ाइल जोड़ें, या एडिट करते समय फ़ॉन्ट टैब के आख़िर में + कार्ड से।"),
     ("अपना डेटा कैसे डिलीट करें?", "होम से थ्री डिलीट करें, या ऐप ही डिलीट कर दें। सब कुछ आपके डिवाइस पर ही है, इसलिए कहीं और कुछ नहीं बचता।")],
    "संपर्क", "कोई बग मिला या कोई सवाल है? एक issue खोलें, हम वहीं जवाब देंगे।", "GitHub पर issue खोलें",
    "प्राइवेसी पॉलिसी", "सपोर्ट",
    "प्राइवेसी पॉलिसी", f"लागू {EFFECTIVE} से",
    [("छोटे में", "Threes में न कोई अकाउंट है, न अपना कोई सर्वर। आप जो भी रिकॉर्ड करते हैं, आपके डिवाइस पर ही रहता है। हम कोई पर्सनल डेटा इकट्ठा नहीं करते; आपके फ़ोन से बाहर सिर्फ़ गुमनाम यूसेज आँकड़े जाते हैं (देखें: नेटवर्क का इस्तेमाल)।"),
     ("कैमरा और Photos", "Threes क्लिप रिकॉर्ड करने के लिए कैमरा और तैयार वीडियो सेव करने के लिए Photos में जोड़ने की परमिशन माँगता है। कुछ भी कहीं अपलोड नहीं होता।"),
     ("आपके डिवाइस पर डेटा", "क्लिप, थंबनेल, ड्राफ़्ट, आपके जोड़े फ़ॉन्ट और सेटिंग्स सिर्फ़ आपके डिवाइस पर रहते हैं। ऐप में डिलीट करने या ऐप हटाने पर ये मिट जाते हैं।"),
     ("खरीदारी", "Threes Pro Apple के इन-ऐप परचेज़ से बिकता है। पेमेंट Apple संभालता है; हमें आपकी पेमेंट डिटेल या Apple ID कभी नहीं दिखती। खरीदारी रीस्टोर करना भी Apple के ज़रिए ही होता है।"),
     ("नेटवर्क का इस्तेमाल", "ऐप इंटरनेट से सिर्फ़ यह देखने के लिए जुड़ता है कि नया वर्ज़न आया है या नहीं — इसके लिए Apple के App Store से ऐप के अपने आइडेंटिफ़ायर और आपके स्टोर रीजन के बारे में पूछता है, और शायद हमारी होस्टिंग से एक छोटी अपडेट-नोटिस फ़ाइल लाता है। कोई डिवाइस आइडेंटिफ़ायर नहीं भेजा जाता। Threes यह गिनने के लिए Google Analytics for Firebase भी इस्तेमाल करता है कि ऐप कैसे इस्तेमाल हो रहा है: कौन सी स्क्रीन खुलती हैं, कौन से टेम्पलेट और फ़िल्टर चुने जाते हैं, थ्री पूरी हुई या खरीदारी हुई। इसमें एक रैंडम ऐप-इंस्टेंस ID, डिवाइस मॉडल, OS वर्ज़न, भाषा और अनुमानित रीजन Google को जाता है। इसमें आपके वीडियो, फ़ोटो, लेबल या कोई अकाउंट कभी शामिल नहीं होता — अकाउंट है ही नहीं। कोई ऐडवर्टाइज़िंग आइडेंटिफ़ायर इस्तेमाल नहीं होता, और न कोई विज्ञापन या क्रॉस-ऐप ट्रैकिंग है।"),
     ("शेयरिंग", "जब आप वीडियो शेयर करते हैं, वह आपके चुने ऐप को सौंप दिया जाता है, और उस ऐप की प्राइवेसी पॉलिसी लागू होती है।"),
     ("बच्चे", "Threes 13 साल से छोटे बच्चों के लिए नहीं है और, जैसा ऊपर बताया, किसी से भी कोई पर्सनल डेटा इकट्ठा नहीं करता।"),
     ("बदलाव", "अगर यह पॉलिसी बदलती है, तो नया वर्ज़न नई लागू तारीख़ के साथ इसी पेज पर डाला जाएगा।"),
     ("संपर्क", f"प्राइवेसी से जुड़े सवाल: {ISSUES} पर issue खोलें।")],
    ""),
"it": C("Assistenza Threes", "Tre clip da 3 secondi, unite in un videodiario verticale.",
    [("Come si registra?", "Tocca il pulsante di registrazione. Registra per 3 secondi e si ferma da solo. Fallo tre volte e il tuo tris è pronto. Puoi anche prendere un video o una foto dall'album."),
     ("Dove sono i miei video?", "Tocca Salva video nella schermata finale e finisce nell'app Foto come mp4 9:16 senza watermark. Le clip restano solo sul tuo telefono."),
     ("Per quanto restano le bozze?", "La versione gratis tiene fino a 3 bozze per 14 giorni. Pro tiene bozze illimitate per 90 giorni. Un tris finito si può rimodificare per 7 giorni."),
     ("Cosa include Pro e come lo ripristino?", "Threes Pro è un acquisto una tantum tramite Apple: etichette personalizzate (i 16 template sono già gratis), 8 filtri in più con controllo dell'intensità, bozze illimitate. Per ripristinarlo su un altro dispositivo, accedi con lo stesso ID Apple e tocca Impostazioni → Ripristina acquisti."),
     ("Posso usare un font mio?", "Sì. Aggiungi un file ttf o otf in Impostazioni → I miei font, oppure con la card + in fondo alla scheda Font mentre modifichi."),
     ("Come elimino i miei dati?", "Elimina un tris dalla Home, oppure elimina l'app. Tutto vive sul tuo dispositivo, quindi non resta nulla da nessun'altra parte.")],
    "Contatti", "Hai trovato un bug o hai una domanda? Apri una issue e ti rispondiamo lì.", "Apri una issue su GitHub",
    "Privacy Policy", "Assistenza",
    "Privacy Policy", f"In vigore dal {EFFECTIVE}",
    [("In breve", "Threes non ha account né server propri. Tutto ciò che registri resta sul tuo dispositivo. Non raccogliamo dati personali; l'unica cosa che esce dal telefono sono statistiche d'uso anonime (vedi Uso della rete)."),
     ("Fotocamera e Foto", "Threes chiede la fotocamera per registrare le clip e il permesso di aggiungere a Foto per salvare il video finito. Niente viene caricato da nessuna parte."),
     ("Dati sul tuo dispositivo", "Clip, anteprime, bozze, font che aggiungi e impostazioni sono salvati solo sul tuo dispositivo. Vengono rimossi quando li elimini nell'app o elimini l'app."),
     ("Acquisti", "Threes Pro è venduto tramite l'acquisto in-app di Apple. Il pagamento lo gestisce Apple; noi non vediamo mai i tuoi dati di pagamento né l'ID Apple. Anche il ripristino dell'acquisto passa da Apple."),
     ("Uso della rete", "L'app si collega a internet solo per controllare se esiste una versione più recente, chiedendo all'App Store di Apple l'identificativo dell'app e la tua regione dello store, ed eventualmente scaricando un piccolo file di avviso aggiornamento dal nostro hosting. Non viene inviato nessun identificativo del dispositivo. Threes usa anche Google Analytics for Firebase per contare come viene usata l'app: quali schermate si aprono, quali template e filtri vengono scelti, se un tris viene completato o viene fatto un acquisto. Questo invia a Google un ID casuale dell'istanza dell'app, il modello del dispositivo, la versione del sistema, la lingua e la regione approssimativa. Non include mai i tuoi video, foto, etichette o alcun account: non ce n'è uno. Non viene usato nessun identificativo pubblicitario e non c'è pubblicità né tracciamento tra app."),
     ("Condivisione", "Quando condividi un video, viene passato all'app che scegli e vale la privacy policy di quell'app."),
     ("Minori", "Threes non è rivolto ai minori di 13 anni e, come descritto sopra, non raccoglie dati personali da nessuno."),
     ("Modifiche", "Se questa policy cambia, la nuova versione sarà pubblicata su questa pagina con una nuova data di validità."),
     ("Contatti", f"Domande sulla privacy: apri una issue su {ISSUES}.")],
    ""),
"ms": C("Sokongan Threes", "Tiga klip 3 saat, disusun jadi satu diari video menegak.",
    [("Macam mana nak rakam?", "Ketik butang rakam. Ia merakam 3 saat dan berhenti sendiri. Buat tiga kali dan 3 klip anda siap. Anda juga boleh ambil video atau foto dari album."),
     ("Video saya ada di mana?", "Ketik Simpan video di skrin siap dan ia masuk ke app Foto sebagai mp4 9:16 tanpa tera air. Klip disimpan di telefon anda saja."),
     ("Draf disimpan berapa lama?", "Percuma simpan sampai 3 draf selama 14 hari. Pro simpan draf tanpa had selama 90 hari. 3 klip yang dah siap boleh diedit semula selama 7 hari."),
     ("Apa yang ada dalam Pro, dan macam mana nak pulihkan?", "Threes Pro ialah pembelian sekali melalui Apple: label custom (semua 16 templat memang dah percuma), 8 filter lagi dengan kawalan kekuatan, draf tanpa had. Untuk pulihkan di peranti lain, log masuk dengan Apple ID yang sama dan ketik Tetapan → Pulihkan pembelian."),
     ("Boleh guna fon sendiri?", "Boleh. Tambah fail ttf atau otf di Tetapan → Fon saya, atau melalui kad + di hujung tab Fon semasa mengedit."),
     ("Macam mana nak padam data saya?", "Padam 3 klip dari Laman Utama, atau padam app ini. Semuanya ada di peranti anda, jadi tiada apa yang tinggal di tempat lain.")],
    "Hubungi", "Jumpa bug atau ada soalan? Buka issue dan kami balas di situ.", "Buka issue di GitHub",
    "Dasar Privasi", "Sokongan",
    "Dasar Privasi", f"Berkuat kuasa {EFFECTIVE}",
    [("Ringkasnya", "Threes tiada akaun dan tiada pelayan sendiri. Semua yang anda rakam kekal di peranti anda. Kami tak kumpul data peribadi; satu-satunya yang keluar dari telefon anda ialah statistik penggunaan tanpa nama (lihat Penggunaan rangkaian)."),
     ("Kamera dan Foto", "Threes minta akses kamera untuk merakam klip anda dan kebenaran menambah ke Foto supaya ia boleh simpan video yang dah siap. Tiada apa yang dimuat naik ke mana-mana."),
     ("Data di peranti anda", "Klip, thumbnail, draf, fon yang anda tambah dan tetapan anda disimpan di peranti anda saja. Ia dibuang bila anda padam dalam app atau padam app ini."),
     ("Pembelian", "Threes Pro dijual melalui Pembelian Dalam App Apple. Apple uruskan pembayaran; kami tak pernah nampak butiran pembayaran atau Apple ID anda. Pemulihan pembelian juga melalui Apple."),
     ("Penggunaan rangkaian", "App ini sambung ke internet hanya untuk semak sama ada versi baru wujud, dengan bertanya App Store Apple tentang pengecam app ini sendiri dan rantau stor anda, dan mungkin dengan mengambil fail notis kemas kini yang kecil dari hos kami. Tiada pengecam peranti dihantar. Threes juga guna Google Analytics for Firebase untuk mengira cara app digunakan: skrin mana dibuka, templat dan filter mana dipilih, sama ada 3 klip disiapkan atau pembelian dibuat. Ini menghantar ID instans app rawak, model peranti, versi OS, bahasa dan rantau anggaran kepada Google. Ia tak pernah termasuk video, foto, label atau mana-mana akaun anda — memang tiada akaun. Tiada pengecam pengiklanan digunakan dan tiada pengiklanan atau penjejakan merentas app."),
     ("Perkongsian", "Bila anda kongsi video, ia diserahkan kepada app yang anda pilih, dan dasar privasi app itu terpakai."),
     ("Kanak-kanak", "Threes bukan untuk kanak-kanak bawah 13 tahun dan, seperti yang dinyatakan di atas, tak kumpul data peribadi daripada sesiapa pun."),
     ("Perubahan", "Jika dasar ini berubah, versi baru akan disiarkan di halaman ini dengan tarikh kuat kuasa yang baru."),
     ("Hubungi", f"Soalan tentang privasi: buka issue di {ISSUES}.")],
    ""),
"nl": C("Threes Support", "Drie clips van 3 seconden, gestapeld tot één verticaal videodagboek.",
    [("Hoe neem ik op?", "Tik op de opnameknop. Die neemt 3 seconden op en stopt vanzelf. Doe dat drie keer en je drieluik is klaar. Je kunt ook een video of foto uit je album halen."),
     ("Waar staan mijn video's?", "Tik op Video opslaan op het eindscherm en de video gaat als 9:16-mp4 zonder watermerk naar de Foto's-app. Clips staan alleen op je telefoon."),
     ("Hoe lang blijven concepten bewaard?", "Gratis bewaart maximaal 3 concepten, 14 dagen lang. Pro bewaart onbeperkt concepten, 90 dagen lang. Een afgerond drieluik kun je 7 dagen lang nog bewerken."),
     ("Wat zit er in Pro en hoe herstel ik het?", "Threes Pro is een eenmalige aankoop via Apple: eigen labels (alle 16 templates zijn al gratis), 8 extra filters met sterkte-instelling, onbeperkt concepten. Om te herstellen op een ander toestel log je in met dezelfde Apple ID en tik je op Instellingen → Aankopen herstellen."),
     ("Kan ik mijn eigen lettertype gebruiken?", "Ja. Voeg een ttf- of otf-bestand toe via Instellingen → Mijn lettertypes, of met de +-kaart aan het eind van het tabblad Lettertype tijdens het bewerken."),
     ("Hoe verwijder ik mijn gegevens?", "Verwijder een drieluik op Home, of verwijder de app. Alles staat op je toestel, dus er blijft nergens anders iets achter.")],
    "Contact", "Een bug gevonden of een vraag? Open een issue, we reageren daar.", "Open een issue op GitHub",
    "Privacybeleid", "Support",
    "Privacybeleid", f"Geldig vanaf {EFFECTIVE}",
    [("In het kort", "Threes heeft geen account en geen eigen server. Alles wat je opneemt blijft op je toestel. We verzamelen geen persoonsgegevens; het enige dat je telefoon verlaat, zijn anonieme gebruiksstatistieken (zie Netwerkgebruik)."),
     ("Camera en Foto's", "Threes vraagt om de camera om je clips op te nemen en om toestemming om aan Foto's toe te voegen, zodat je afgeronde video bewaard kan worden. Er wordt niets ergens geüpload."),
     ("Gegevens op je toestel", "Clips, thumbnails, concepten, lettertypes die je toevoegt en je instellingen staan alleen op je toestel. Ze worden verwijderd als je ze in de app verwijdert of de app verwijdert."),
     ("Aankopen", "Threes Pro wordt verkocht via Apple's In-App Purchase. Apple regelt de betaling; wij zien nooit je betaalgegevens of Apple ID. Een aankoop herstellen gaat ook via Apple."),
     ("Netwerkgebruik", "De app maakt alleen verbinding met internet om te checken of er een nieuwere versie is, door Apple's App Store te vragen naar de eigen identifier van de app en je storeregio, en mogelijk door een klein update-bestand van onze hosting op te halen. Er worden geen toestel-identifiers verstuurd. Threes gebruikt ook Google Analytics for Firebase om te tellen hoe de app gebruikt wordt: welke schermen openen, welke templates en filters gekozen worden, of een drieluik wordt afgerond of een aankoop wordt gedaan. Hierbij worden een willekeurige app-instantie-ID, toestelmodel, OS-versie, taal en globale regio naar Google gestuurd. Het bevat nooit je video's, foto's, labels of een account — dat is er niet. Er wordt geen advertentie-identifier gebruikt en er is geen reclame of tracking tussen apps."),
     ("Delen", "Als je een video deelt, wordt die doorgegeven aan de app die je kiest, en dan geldt het privacybeleid van die app."),
     ("Kinderen", "Threes is niet gericht op kinderen onder de 13 en verzamelt, zoals hierboven beschreven, van niemand persoonsgegevens."),
     ("Wijzigingen", "Als dit beleid verandert, wordt de nieuwe versie op deze pagina gezet met een nieuwe ingangsdatum."),
     ("Contact", f"Vragen over privacy: open een issue op {ISSUES}.")],
    ""),
"pl": C("Threes – pomoc", "Trzy 3-sekundowe klipy, ułożone w jeden pionowy dziennik wideo.",
    [("Jak nagrywać?", "Stuknij przycisk nagrywania. Nagrywa 3 sekundy i sam się zatrzymuje. Zrób tak trzy razy i twoja trójka jest gotowa. Możesz też wciągnąć wideo lub zdjęcie z albumu."),
     ("Gdzie są moje filmy?", "Na ekranie końcowym stuknij Zapisz wideo, a trafi do aplikacji Zdjęcia jako mp4 9:16 bez znaku wodnego. Klipy są przechowywane tylko na twoim telefonie."),
     ("Jak długo trzymane są szkice?", "Wersja darmowa trzyma do 3 szkiców przez 14 dni. Pro trzyma szkice bez limitu przez 90 dni. Gotową trójkę można edytować ponownie przez 7 dni."),
     ("Co zawiera Pro i jak je przywrócić?", "Threes Pro to jednorazowy zakup przez Apple: własne etykiety (wszystkie 16 szablonów jest już darmowych), 8 filtrów więcej z regulacją mocy, szkice bez limitu. Żeby przywrócić zakup na innym urządzeniu, zaloguj się tym samym Apple ID i stuknij Ustawienia → Przywróć zakupy."),
     ("Mogę użyć własnej czcionki?", "Tak. Dodaj plik ttf lub otf w Ustawienia → Moje czcionki albo kartą + na końcu zakładki Czcionka podczas edycji."),
     ("Jak usunąć moje dane?", "Usuń trójkę z ekranu głównego albo usuń aplikację. Wszystko jest na twoim urządzeniu, więc nigdzie indziej nic nie zostaje.")],
    "Kontakt", "Znalazłeś błąd albo masz pytanie? Otwórz zgłoszenie, odpowiemy tam.", "Otwórz zgłoszenie na GitHubie",
    "Polityka prywatności", "Pomoc",
    "Polityka prywatności", f"Obowiązuje od {EFFECTIVE}",
    [("W skrócie", "Threes nie ma konta ani własnego serwera. Wszystko, co nagrywasz, zostaje na twoim urządzeniu. Nie zbieramy danych osobowych; jedyne, co opuszcza twój telefon, to anonimowe statystyki użycia (zobacz Połączenia sieciowe)."),
     ("Aparat i Zdjęcia", "Threes prosi o dostęp do aparatu, by nagrywać klipy, oraz o zgodę na dodawanie do Zdjęć, by zapisać gotowe wideo. Nic nie jest nigdzie wysyłane."),
     ("Dane na twoim urządzeniu", "Klipy, miniatury, szkice, dodane czcionki i ustawienia są przechowywane tylko na twoim urządzeniu. Znikają, gdy usuniesz je w aplikacji albo usuniesz aplikację."),
     ("Zakupy", "Threes Pro jest sprzedawane przez zakupy w aplikacji Apple. Płatność obsługuje Apple; nigdy nie widzimy twoich danych płatniczych ani Apple ID. Przywracanie zakupu też idzie przez Apple."),
     ("Połączenia sieciowe", "Aplikacja łączy się z internetem tylko po to, by sprawdzić, czy jest nowsza wersja: pyta App Store Apple o własny identyfikator aplikacji i twój region sklepu, a czasem pobiera mały plik z informacją o aktualizacji z naszego hostingu. Nie są wysyłane żadne identyfikatory urządzenia. Threes używa też Google Analytics for Firebase, by liczyć, jak aplikacja jest używana: które ekrany się otwierają, które szablony i filtry są wybierane, czy trójka została ukończona lub czy dokonano zakupu. Do Google trafia losowy identyfikator instancji aplikacji, model urządzenia, wersja systemu, język i przybliżony region. Nigdy nie zawiera to twoich filmów, zdjęć, etykiet ani żadnego konta — bo go nie ma. Nie używamy identyfikatora reklamowego, nie ma reklam ani śledzenia między aplikacjami."),
     ("Udostępnianie", "Gdy udostępniasz wideo, trafia ono do wybranej przez ciebie aplikacji i obowiązuje wtedy jej polityka prywatności."),
     ("Dzieci", "Threes nie jest skierowane do dzieci poniżej 13 lat i, jak opisano wyżej, nie zbiera danych osobowych od nikogo."),
     ("Zmiany", "Jeśli ta polityka się zmieni, nowa wersja pojawi się na tej stronie z nową datą obowiązywania."),
     ("Kontakt", f"Pytania o prywatność: otwórz zgłoszenie na {ISSUES}.")],
    ""),
"ru": C("Поддержка Threes", "Три клипа по 3 секунды, собранные в один вертикальный видеодневник.",
    [("Как записывать?", "Тапни кнопку записи. Запись идёт 3 секунды и останавливается сама. Повтори три раза — и тройка готова. Видео или фото можно также взять из галереи."),
     ("Где мои видео?", "На экране готовой тройки тапни «Сохранить видео» — ролик уйдёт в приложение Фото как mp4 9:16 без водяных знаков. Клипы хранятся только на твоём телефоне."),
     ("Сколько хранятся черновики?", "Бесплатно — до 3 черновиков на 14 дней. В Pro — черновики без лимита на 90 дней. Готовую тройку можно снова отредактировать в течение 7 дней."),
     ("Что входит в Pro и как его восстановить?", "Threes Pro — разовая покупка через Apple: свои надписи (все 16 шаблонов и так бесплатны), ещё 8 фильтров с регулировкой силы, черновики без лимита. Чтобы восстановить на другом устройстве, войди с тем же Apple ID и тапни Настройки → Восстановить покупки."),
     ("Можно свой шрифт?", "Да. Добавь файл ttf или otf в Настройки → Мои шрифты или через карточку «+» в конце вкладки «Шрифт» при редактировании."),
     ("Как удалить свои данные?", "Удали тройку на главной или удали приложение. Всё живёт на твоём устройстве, так что больше нигде ничего не остаётся.")],
    "Контакты", "Есть баг или вопрос? Открой issue — ответим там.", "Открыть issue на GitHub",
    "Политика конфиденциальности", "Поддержка",
    "Политика конфиденциальности", f"Действует с {EFFECTIVE}",
    [("Коротко", "У Threes нет ни аккаунта, ни собственного сервера. Всё, что ты снимаешь, остаётся на твоём устройстве. Мы не собираем персональные данные; с телефона уходит только анонимная статистика использования (см. «Сеть»)."),
     ("Камера и Фото", "Threes запрашивает камеру, чтобы записывать клипы, и разрешение на добавление в Фото, чтобы сохранять готовое видео. Ничего никуда не загружается."),
     ("Данные на устройстве", "Клипы, миниатюры, черновики, добавленные шрифты и настройки хранятся только на твоём устройстве. Они удаляются, когда ты удаляешь их в приложении или удаляешь само приложение."),
     ("Покупки", "Threes Pro продаётся через встроенные покупки Apple. Оплату проводит Apple; мы не видим ни платёжные данные, ни Apple ID. Восстановление покупки тоже идёт через Apple."),
     ("Сеть", "Приложение выходит в интернет только чтобы проверить, нет ли новой версии: спрашивает App Store по идентификатору самого приложения и региону твоего магазина и, возможно, загружает небольшой файл с уведомлением об обновлении с нашего хостинга. Идентификаторы устройства не отправляются. Ещё Threes использует Google Analytics for Firebase, чтобы считать, как пользуются приложением: какие экраны открывают, какие шаблоны и фильтры выбирают, завершена ли тройка, сделана ли покупка. В Google при этом уходят случайный ID экземпляра приложения, модель устройства, версия ОС, язык и примерный регион. Твои видео, фото, надписи и аккаунт туда не попадают никогда — аккаунта и нет. Рекламный идентификатор не используется, рекламы и отслеживания между приложениями нет."),
     ("Шеринг", "Когда ты делишься видео, оно передаётся выбранному приложению, и дальше действует его политика конфиденциальности."),
     ("Дети", "Threes не предназначен для детей младше 13 лет и, как описано выше, не собирает персональные данные ни у кого."),
     ("Изменения", "Если политика изменится, новая версия появится на этой странице с новой датой вступления в силу."),
     ("Контакты", f"Вопросы о конфиденциальности: открой issue на {ISSUES}.")],
    ""),
"sv": C("Threes support", "Tre 3-sekundersklipp, staplade till en stående videodagbok.",
    [("Hur spelar jag in?", "Tryck på inspelningsknappen. Den filmar i 3 sekunder och stannar av sig själv. Gör det tre gånger så är din trea klar. Du kan också hämta en video eller ett foto från albumet."),
     ("Var hamnar mina videor?", "Tryck på Spara video på slutskärmen så hamnar den i appen Bilder som en 9:16-mp4 utan vattenstämpel. Klippen lagras bara på din telefon."),
     ("Hur länge sparas utkast?", "Gratis sparar upp till 3 utkast i 14 dagar. Pro sparar obegränsat med utkast i 90 dagar. En färdig trea kan redigeras igen i 7 dagar."),
     ("Vad ingår i Pro, och hur återställer jag det?", "Threes Pro är ett engångsköp via Apple: egna etiketter (alla 16 mallar är redan gratis), 8 filter till med styrkereglage, obegränsat med utkast. För att återställa på en annan enhet loggar du in med samma Apple-ID och trycker på Inställningar → Återställ köp."),
     ("Kan jag använda mitt eget typsnitt?", "Ja. Lägg till en ttf- eller otf-fil i Inställningar → Mina typsnitt, eller med +-kortet längst bak i fliken Typsnitt när du redigerar."),
     ("Hur raderar jag min data?", "Radera en trea från startsidan, eller radera appen. Allt ligger på din enhet, så inget finns kvar någon annanstans.")],
    "Kontakt", "Hittat en bugg eller har du en fråga? Öppna ett ärende så svarar vi där.", "Öppna ett ärende på GitHub",
    "Integritetspolicy", "Support",
    "Integritetspolicy", f"Gäller från {EFFECTIVE}",
    [("Kort sagt", "Threes har inget konto och ingen egen server. Allt du spelar in stannar på din enhet. Vi samlar inte in personuppgifter; det enda som lämnar din telefon är anonym användningsstatistik (se Nätverksanvändning)."),
     ("Kamera och Bilder", "Threes ber om kameran för att spela in dina klipp och om tillstånd att lägga till i Bilder för att kunna spara din färdiga video. Inget laddas upp någonstans."),
     ("Data på din enhet", "Klipp, miniatyrer, utkast, typsnitt du lägger till och dina inställningar lagras bara på din enhet. De tas bort när du raderar dem i appen eller raderar appen."),
     ("Köp", "Threes Pro säljs via Apples köp i appen. Apple sköter betalningen; vi ser aldrig dina betaluppgifter eller ditt Apple-ID. Att återställa ett köp går också via Apple."),
     ("Nätverksanvändning", "Appen ansluter till internet bara för att kolla om det finns en nyare version, genom att fråga Apples App Store om appens egen identifierare och din butiksregion, och eventuellt genom att hämta en liten uppdateringsfil från vår hosting. Inga enhetsidentifierare skickas. Threes använder också Google Analytics för Firebase för att räkna hur appen används: vilka skärmar som öppnas, vilka mallar och filter som väljs, om en trea slutförs eller ett köp görs. Det skickar ett slumpmässigt app-instans-ID, enhetsmodell, OS-version, språk och ungefärlig region till Google. Det innehåller aldrig dina videor, foton, etiketter eller något konto — det finns inget. Ingen reklamidentifierare används och det finns ingen reklam eller spårning mellan appar."),
     ("Delning", "När du delar en video lämnas den över till appen du väljer, och den appens integritetspolicy gäller."),
     ("Barn", "Threes riktar sig inte till barn under 13 år och samlar, som beskrivet ovan, inte in personuppgifter från någon."),
     ("Ändringar", "Om den här policyn ändras publiceras den nya versionen på den här sidan med ett nytt startdatum."),
     ("Kontakt", f"Frågor om integritet: öppna ett ärende på {ISSUES}.")],
    ""),
"tr": C("Threes Destek", "3 saniyelik üç klip, üst üste dizilmiş tek bir dikey video günlük.",
    [("Nasıl kayıt yaparım?", "Kayıt düğmesine dokun. 3 saniye kaydeder ve kendi durur. Bunu üç kez yap, üçlün hazır. Albümünden de video ya da fotoğraf alabilirsin."),
     ("Videolarım nerede?", "Bitiş ekranında Videoyu kaydet'e dokun; filigransız 9:16 mp4 olarak Fotoğraflar uygulamasına gider. Klipler sadece telefonunda saklanır."),
     ("Taslaklar ne kadar saklanır?", "Ücretsiz sürüm en fazla 3 taslağı 14 gün saklar. Pro sınırsız taslağı 90 gün saklar. Biten bir üçlü 7 gün boyunca yeniden düzenlenebilir."),
     ("Pro neleri içerir, nasıl geri yüklerim?", "Threes Pro, Apple üzerinden tek seferlik bir satın almadır: özel etiketler (16 şablonun hepsi zaten ücretsiz), yoğunluk ayarlı 8 filtre daha, sınırsız taslak. Başka bir cihazda geri yüklemek için aynı Apple Kimliği ile giriş yap ve Ayarlar → Satın almaları geri yükle'ye dokun."),
     ("Kendi fontumu kullanabilir miyim?", "Evet. Ayarlar → Fontlarım'dan ya da düzenlerken Font sekmesinin sonundaki + kartıyla ttf veya otf dosyası ekle."),
     ("Verilerimi nasıl silerim?", "Ana ekrandan bir üçlüyü sil ya da uygulamayı sil. Her şey cihazında durur; başka hiçbir yerde bir şey kalmaz.")],
    "İletişim", "Hata mı buldun, sorun mu var? Bir issue aç, orada yanıtlayalım.", "GitHub'da issue aç",
    "Gizlilik Politikası", "Destek",
    "Gizlilik Politikası", f"Yürürlük tarihi: {EFFECTIVE}",
    [("Kısaca", "Threes'in hesabı da kendi sunucusu da yok. Kaydettiğin her şey cihazında kalır. Kişisel veri toplamıyoruz; telefonundan çıkan tek şey anonim kullanım istatistikleridir (bkz. Ağ kullanımı)."),
     ("Kamera ve Fotoğraflar", "Threes, kliplerini çekmek için kamera izni, biten videonu kaydetmek için de Fotoğraflar'a ekleme izni ister. Hiçbir şey hiçbir yere yüklenmez."),
     ("Cihazındaki veriler", "Klipler, küçük resimler, taslaklar, eklediğin fontlar ve ayarların sadece cihazında saklanır. Uygulamadan sildiğinde ya da uygulamayı sildiğinde kaldırılır."),
     ("Satın almalar", "Threes Pro, Apple'ın Uygulama İçi Satın Alma sistemiyle satılır. Ödemeyi Apple yürütür; ödeme bilgilerini ya da Apple Kimliğini asla görmeyiz. Satın alma geri yükleme de Apple üzerinden yapılır."),
     ("Ağ kullanımı", "Uygulama internete yalnızca yeni bir sürüm var mı diye bakmak için bağlanır: Apple App Store'a uygulamanın kendi kimliğini ve mağaza bölgeni sorar ve gerekirse barındırma sunucumuzdan küçük bir güncelleme bildirimi dosyası indirir. Cihaz kimliği gönderilmez. Threes ayrıca uygulamanın nasıl kullanıldığını saymak için Google Analytics for Firebase kullanır: hangi ekranlar açılıyor, hangi şablon ve filtreler seçiliyor, bir üçlü bitiriliyor ya da satın alma yapılıyor mu. Bu, Google'a rastgele bir uygulama örneği kimliği, cihaz modeli, işletim sistemi sürümü, dil ve yaklaşık bölge gönderir. Videoların, fotoğrafların, etiketlerin ya da herhangi bir hesap asla dahil değildir — zaten hesap yok. Reklam kimliği kullanılmaz; reklam ya da uygulamalar arası takip yoktur."),
     ("Paylaşım", "Bir videoyu paylaştığında seçtiğin uygulamaya iletilir ve o uygulamanın gizlilik politikası geçerli olur."),
     ("Çocuklar", "Threes 13 yaş altı çocuklara yönelik değildir ve yukarıda anlatıldığı gibi kimseden kişisel veri toplamaz."),
     ("Değişiklikler", "Bu politika değişirse yeni sürümü yeni yürürlük tarihiyle bu sayfada yayımlanır."),
     ("İletişim", f"Gizlilikle ilgili sorular için {ISSUES} adresinde bir issue aç.")],
    ""),
}

CSS = """
:root{--paper:#FAFAF8;--card:#F0EFEC;--line:#D9D6CF;--ink:#2B2926;--soft:#6F6B64;--faint:#A9A49B;--pink:#F58BB4;--butter:#F7E08A}
*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:17px/1.65 -apple-system,BlinkMacSystemFont,"Pretendard","Apple SD Gothic Neo","Hiragino Sans","PingFang SC","PingFang TC","Thonburi","Segoe UI",Roboto,sans-serif}
main{max-width:680px;margin:0 auto;padding:40px 20px 80px}
.brand{font-weight:800;font-size:28px;letter-spacing:-.02em;text-decoration:none;color:var(--ink)}
.brand span{display:inline-block;width:12px;height:12px;border-radius:50%;background:var(--pink);margin-left:6px;vertical-align:middle}
nav{display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap;margin-bottom:36px}
nav a{color:var(--soft);text-decoration:none;font-size:15px}nav a:hover{color:var(--ink)}
select{font:inherit;font-size:14px;color:var(--soft);background:var(--card);border:1px solid var(--line);border-radius:10px;padding:6px 10px}
h1{font-size:34px;line-height:1.2;letter-spacing:-.02em;margin:0 0 8px}
.tag{color:var(--soft);margin:0 0 32px}.eff{color:var(--faint);font-size:14px;margin:0 0 32px}
h2{font-size:19px;margin:32px 0 6px}p{margin:0 0 12px}
details{background:var(--card);border-radius:14px;padding:14px 18px;margin:10px 0}summary{font-weight:600;cursor:pointer}details p{margin:10px 0 2px;color:var(--soft)}
.btn{display:inline-block;background:var(--ink);color:#fff;text-decoration:none;padding:12px 18px;border-radius:999px;font-weight:600;margin-top:6px}
footer{margin-top:56px;color:var(--faint);font-size:14px}footer a{color:var(--soft)}
mark{background:var(--butter);padding:0 4px;border-radius:4px}
"""

def switcher(lang, page):
    opts = "".join(f'<option value="{code}"{" selected" if code == lang else ""}>{name}</option>' for code, name in LANG_NAMES.items())
    return f'<select onchange="location.href=\'../\'+this.value+\'/{page}\'" aria-label="Language">{opts}</select>'

def shell(lang, title, page, body, other_link):
    return f"""<!doctype html>
<html lang="{lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{html.escape(title)} · Threes</title><style>{CSS}</style></head>
<body><main>
<nav><a class="brand" href="./">Threes<span></span></a><div>{other_link} &nbsp; {switcher(lang, page)}</div></nav>
{body}
<footer>Threes · <a href="{APP_STORE}">App Store</a> · <a href="https://github.com/ohtt-iOS/Threes-public">GitHub</a></footer>
</main></body></html>
"""

def support_page(lang, c):
    faq = "".join(f"<details><summary>{html.escape(q)}</summary><p>{html.escape(a)}</p></details>" for q, a in c["faq"])
    body = f"""<h1>{html.escape(c['support_title'])}</h1><p class="tag">{html.escape(c['tagline'])}</p>
{faq}
<h2>{html.escape(c['contact_h'])}</h2><p>{html.escape(c['contact_p'])}</p>
<a class="btn" href="{ISSUES}">{html.escape(c['contact_link'])}</a>"""
    return shell(lang, c["support_title"], "index.html", body, f'<a href="privacy.html">{html.escape(c["privacy_link"])}</a>')

def privacy_page(lang, c):
    secs = "".join(f"<h2>{html.escape(h)}</h2><p>{html.escape(p).replace(html.escape(ISSUES), f'<a href={chr(34)}{ISSUES}{chr(34)}>{ISSUES}</a>')}</p>" for h, p in c["sections"])
    body = f"""<h1>{html.escape(c['privacy_title'])}</h1><p class="eff">{html.escape(c['effective'])}</p>{secs}"""
    return shell(lang, c["privacy_title"], "privacy.html", body, f'<a href="./">{html.escape(c["support_link"])}</a>')

def redirect_page(page):
    codes = list(LANG_NAMES)
    return f"""<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Threes</title><meta http-equiv="refresh" content="1;url=en/{page}">
<script>
var langs={codes!r};var want=(navigator.languages||[navigator.language||'en']).map(function(l){{return l.toLowerCase()}});
var pick='en';outer:for(var i=0;i<want.length;i++){{var w=want[i];
 if(w.indexOf('zh')===0){{pick=(w.indexOf('hant')>-1||w.indexOf('tw')>-1||w.indexOf('hk')>-1||w.indexOf('mo')>-1)?'zh-Hant':'zh-Hans';break}}
 if(w.indexOf('pt')===0){{pick='pt-BR';break}}
 for(var j=0;j<langs.length;j++){{if(w===langs[j].toLowerCase()||w.split('-')[0]===langs[j].toLowerCase()){{pick=langs[j];break outer}}}}}}
location.replace(pick+'/{page}');
</script></head><body><a href="en/{page}">Threes</a></body></html>
"""

if __name__ == "__main__":
    for lang, c in CONTENT.items():
        d = ROOT / lang; d.mkdir(exist_ok=True)
        (d / "index.html").write_text(support_page(lang, c), encoding="utf-8")
        (d / "privacy.html").write_text(privacy_page(lang, c), encoding="utf-8")
    (ROOT / "index.html").write_text(redirect_page("index.html"), encoding="utf-8")
    (ROOT / "privacy.html").write_text(redirect_page("privacy.html"), encoding="utf-8")
    (ROOT / ".nojekyll").write_text("")
    print("built:", ", ".join(CONTENT))
